id: I8DAB94BC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:11:54+00:00'
last_modified: '2022-06-09T07:10:21.621840+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17947
  title: དབུ་མ་འཇུག་པ། མངོན་རྟོགས་རྒྱན། མཛོད། འདུལ་བ་དང་རྣམ་འགྲེལ་བཅས་ཀྱི་རྩ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2BC6:
      image_group_id: I8LS17955
      title: Volume 1 of dbu ma 'jug pa/ mngon rtogs rgyan/ mdzod/ 'dul ba dang rnam
        'grel bcas kyi rtsa ba/
      total_pages: 641
      order: 1
      base_file: 2BC6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
