id: P007894
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS17947
  title: དབུ་མ་འཇུག་པ། མངོན་རྟོགས་རྒྱན། མཛོད། འདུལ་བ་དང་རྣམ་འགྲེལ་བཅས་ཀྱི་རྩ་བ།
  author: ''
  volumes:
    7001a92248f04d45917a90cb6e3f571b:
      image_group_id: I8LS17955
      title: Volume 1 of dbu ma 'jug pa/ mngon rtogs rgyan/ mdzod/ 'dul ba dang rnam
        'grel bcas kyi rtsa ba/
      volume_number: 1
      total_pages: 641
      base_file: v001.txt
