id: P007894
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17947
  title: དབུ་མ་འཇུག་པ། མངོན་རྟོགས་རྒྱན། མཛོད། འདུལ་བ་དང་རྣམ་འགྲེལ་བཅས་ཀྱི་རྩ་བ།
  author: ''
  volumes:
    ee035b51f57d40fd8368822072bcbb05:
      image_group_id: I8LS17955
      title: ''
      volume_number: 1
      total_pages: 641
ebook_metadata:
  title: དབུ་མ་འཇུག་པ། མངོན་རྟོགས་རྒྱན། མཛོད། འདུལ་བ་དང་རྣམ་འགྲེལ་བཅས་ཀྱི་རྩ་བ།
  author: ''
  sku: P007894
  cover: cover.jpg
  layers:
  - pagination
